name: Build CI wheels

on:
  push

jobs:
  build_linux_37_and_above_wheels:
    name: Build python ${{ matrix.cibw_python }} wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # fail-fast: false
      matrix:
        os: [ubuntu-18.04]
        cibw_python: ["cp39-*"]
        # cibw_manylinux: [ manylinux2014 ]
        cibw_manylinux: [ manylinux_2_24 ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build the wheel
        run: |
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: ${{ matrix.cibw_python }}
          # CIBW_BEFORE_ALL_LINUX: yum install -y libcurl-devel libtiff-devel zlib-devel geos-devel && bash tools/install_proj.sh
          CIBW_BEFORE_ALL_LINUX: apt-get install -y libproj-dev libgeos-dev
          CIBW_ARCHS_LINUX: auto aarch64
          CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.cibw_manylinux }}
          CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.cibw_manylinux }}
      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./dist/*.whl